import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import type { CreativeStrategy, ProductionPackage } from "../runtime/stage-artifacts.js";
import { renderFinalMp4 } from "./ffmpeg.js";
import ffmpegStatic from "ffmpeg-static";

const execFileAsync = promisify(execFile);
export interface ProductionOptions { outputDir?: string; outputMp4?: string; renderImage?: (prompt: string) => Promise<unknown>; renderVideo?: (prompt: string) => Promise<unknown>; generateVoice?: (text: string) => Promise<unknown>; generateSubtitle?: (text: string) => Promise<unknown>; edit?: (input: { image: unknown; video: unknown; voice: unknown; subtitle: unknown }) => Promise<unknown>; }
function buildSubtitle(lines: string[]): string { const safe = lines.slice(0, 5).map((line) => line.trim()).filter(Boolean); const duration = 10 / Math.max(1, safe.length); const stamp = (seconds: number) => { const whole = Math.floor(seconds); const millis = Math.round((seconds - whole) * 1000); return `00:00:${String(whole).padStart(2, "0")},${String(millis).padStart(3, "0")}`; }; return safe.map((line, index) => `${index + 1}\n${stamp(index * duration)} --> ${stamp((index + 1) * duration)}\n${line}\n`).join("\n"); }
function requiredScripts(creative: CreativeStrategy): { voiceScript: string[]; subtitleScript: string[] } { if (!Array.isArray(creative.voiceScript) || creative.voiceScript.length !== 5) throw new Error("Production requires exactly 5 voice-script lines from creative strategy."); if (!Array.isArray(creative.subtitleScript) || creative.subtitleScript.length !== 5) throw new Error("Production requires exactly 5 subtitle-script lines from creative strategy."); return { voiceScript: creative.voiceScript, subtitleScript: creative.subtitleScript }; }
function resolveFfmpeg(): string { return process.env.FFMPEG_BIN?.trim() || ffmpegStatic || "ffmpeg"; }
async function runLocalFfmpeg(args: string[]): Promise<void> { try { await execFileAsync(resolveFfmpeg(), args); } catch (error) { throw new Error(`Local FFmpeg production failed: ${error instanceof Error ? error.message : String(error)}`); } }
async function produceLocalCreative(creative: CreativeStrategy, outputDir: string, outputMp4?: string): Promise<ProductionPackage> { const { voiceScript, subtitleScript } = requiredScripts(creative); await mkdir(outputDir, { recursive: true }); const videoPath = join(outputDir, "video-1.mp4"), voicePath = join(outputDir, "voice.wav"), subtitlePath = join(outputDir, "subtitles.srt"), outputPath = outputMp4 ?? join(outputDir, "final.mp4"); await runLocalFfmpeg(["-y", "-f", "lavfi", "-i", "color=c=black:s=720x1280:d=10", "-r", "30", "-pix_fmt", "yuv420p", videoPath]); await runLocalFfmpeg(["-y", "-f", "lavfi", "-i", "sine=frequency=880:duration=10", "-ar", "44100", voicePath]); await writeFile(subtitlePath, buildSubtitle(subtitleScript), "utf8"); const finalMp4 = await renderFinalMp4({ videoPath, voicePath, subtitlePath, outputPath }); return { image: creative.image, video: creative.video, voice: voiceScript.join("\n"), subtitle: subtitleScript, editing: { type: "editing-manifest", sequence: ["video", "voice", "subtitle"], storyboard: creative.storyboard, prompts: creative.prompt, finalMp4, status: "rendered", localVideoPath: videoPath, localVoicePath: voicePath, localSubtitlePath: subtitlePath } }; }
export async function produceCreative(creative: CreativeStrategy, options: ProductionOptions = {}): Promise<ProductionPackage> { const { voiceScript, subtitleScript } = requiredScripts(creative); const outputDir = options.outputDir ?? process.env.COMMERCA_OUTPUT_DIR ?? "./output"; const hasAdapters = !!options.renderImage || !!options.renderVideo || !!options.generateVoice || !!options.generateSubtitle || !!options.edit; if (!hasAdapters) { if (process.env.COMMERCA_MODE === "live") throw new Error("Live production requires explicit image, video and voice adapters; no Gemini provider is configured."); return produceLocalCreative(creative, outputDir, options.outputMp4); }
  const image = options.renderImage ? await Promise.all(creative.image.map(options.renderImage)) : creative.image;
  const video = options.renderVideo ? await Promise.all(creative.video.map(options.renderVideo)) : creative.video;
  const voice = options.generateVoice ? await options.generateVoice(voiceScript.join("\n")) : voiceScript.join("\n");
  const subtitle = options.generateSubtitle ? await options.generateSubtitle(subtitleScript.join("\n")) : subtitleScript;
  const editingInput = { image, video, voice, subtitle };
  const editing = options.edit ? await options.edit(editingInput) : { storyboard: creative.storyboard, prompts: creative.prompt };
  return { image, video, voice, subtitle, editing };
}
