import { WORKFLOW_STAGES } from "./workflow-schema.js";
import { WorkflowStageRegistry, FunctionStage, artifact } from "./stages.js";
import type { StageContext } from "./stage-contract.js";
import { ProductProviderRegistry, ShopeeBrowserProvider, RakatookyangProvider, rankProducts, readShopeeProductDetail, readRakatookyangPriceHistory, scoreProducts } from "../product/index.js";
import { MarketResearchRegistry, FixtureMarketResearchProvider } from "../market/registry.js";
import { generateContent } from "../content/index.js";
import type { Product } from "../product/types.js";
import type { CreativeStrategy, ProductionPackage, QcReport, PublicationRecord, PerformanceReport, DecisionLearning } from "./stage-artifacts.js";

function productRegistry(): ProductProviderRegistry { const registry = new ProductProviderRegistry(); registry.register(new ShopeeBrowserProvider()); registry.register(new RakatookyangProvider()); return registry; }
function marketRegistry(): MarketResearchRegistry { const registry = new MarketResearchRegistry(); registry.register(new FixtureMarketResearchProvider()); return registry; }
function latest<T>(context: StageContext, type: string): T | undefined { return [...context.artifacts].reverse().find((item) => item.type === type)?.data as T | undefined; }
export interface StageRegistryOptions { discoverProducts?: (goal: string) => Promise<Product[]>; researchProduct?: (product: Product) => Promise<Product>; marketResearch?: (input: { productId?: string; productName: string; query: string }) => ReturnType<MarketResearchRegistry["research"]>; }
async function enrichProduct(product: Product): Promise<Product> { if (!product.url) return product; if (product.source === "shopee-browser" && /shopee\.co\.th/i.test(product.url)) return readShopeeProductDetail(product.url); if (product.source === "rakatookyang" && /shopee\.co\.th/i.test(product.url)) return readRakatookyangPriceHistory(product.url); return product; }

export function createStageRegistry(options: StageRegistryOptions = {}): WorkflowStageRegistry {
  const registry = new WorkflowStageRegistry();
  registry.register(new FunctionStage("goal", async (c) => ({ artifacts: [artifact("goal", "goal", { text: c.goal })] })));
  registry.register(new FunctionStage("product-discovery", async (c) => { const results = options.discoverProducts ? await options.discoverProducts(c.goal) : (await productRegistry().searchAll(c.goal)).flatMap((r) => r.products); const unique = [...new Map(results.map((p) => [p.url || `${p.source}:${p.name}`, p])).values()]; if (!unique.length) throw new Error("Product discovery returned 0 products from configured providers."); return { artifacts: [artifact("product-discovery", "product-candidate-list", unique)] }; }));
  registry.register(new FunctionStage("product-research", async (c) => { const products = latest<Product[]>(c, "product-candidate-list") ?? []; if (!products.length) throw new Error("Product research requires candidates."); const researcher = options.researchProduct ?? enrichProduct; const researched: Product[] = []; const errors: Array<{ productId: string; error: string }> = []; for (const product of products) { try { researched.push(await researcher(product)); } catch (error) { errors.push({ productId: product.id, error: error instanceof Error ? error.message : String(error) }); researched.push(product); } } return { artifacts: [artifact("product-research", "product-profile", { products: researched, researchErrors: errors })] }; }));
  registry.register(new FunctionStage("market-research", async (c) => { const profile = latest<{ products: Product[] }>(c, "product-profile"); const product = profile?.products?.[0]; if (!product) throw new Error("Market research requires researched product."); const evidence = await (options.marketResearch ? options.marketResearch({ productId: product.id, productName: product.name, query: c.goal }) : marketRegistry().research({ productId: product.id, productName: product.name, query: c.goal })); return { artifacts: [artifact("market-research", "market-evidence", { productId: product.id, productName: product.name, evidence })] }; }));
  registry.register(new FunctionStage("product-analysis", async (c) => { const products = latest<{ products: Product[] }>(c, "product-profile")?.products ?? []; if (!products.length) throw new Error("Product analysis requires researched products."); const analysis = rankProducts(products); const market = latest<{ evidence?: unknown }>(c, "market-evidence")?.evidence; return { artifacts: [artifact("product-analysis", "product-analysis", analysis.map((item) => ({ ...item, marketEvidence: market ?? null })))] }; }));
  registry.register(new FunctionStage("product-scoring", async (c) => { const analysis = latest<ReturnType<typeof rankProducts>>(c, "product-analysis") ?? []; if (!analysis.length) throw new Error("Product scoring requires analysis."); const scorecard = scoreProducts(analysis); return { artifacts: [artifact("product-scoring", "scorecard", scorecard)] }; }));
  registry.register(new FunctionStage("product-selection", async (c) => { const scored = latest<Array<{ productId: string; score: number }>>(c, "scorecard") ?? []; const selected = [...scored].sort((a, b) => b.score - a.score)[0]; if (!selected) throw new Error("No product passed selection."); const analysis = latest<ReturnType<typeof rankProducts>>(c, "product-analysis") ?? []; const selectedAnalysis = analysis.find((item) => item.product.id === selected.productId); if (!selectedAnalysis) throw new Error("Selected product analysis is missing."); return { artifacts: [artifact("product-selection", "selection", selectedAnalysis)] }; }));
  registry.register(new FunctionStage("content-strategy", async (c) => { const selected = latest<{ product?: Product }>(c, "selection"); if (!selected?.product) throw new Error("Content strategy requires selection."); return { artifacts: [artifact("content-strategy", "content-package", generateContent(rankProducts([selected.product])[0]))] }; }));
  registry.register(new FunctionStage("creative-strategy", async (c) => ({ artifacts: [artifact("creative-strategy", "creative-strategy", { image: ["product hero"], video: ["short product demonstration"], storyboard: ["hook", "problem", "product", "proof", "CTA"], prompt: [JSON.stringify({ content: latest(c, "content-package"), format: "9:16" })] } satisfies CreativeStrategy)] })));
  registry.register(new FunctionStage("production", async (c) => { const creative = latest<CreativeStrategy>(c, "creative-strategy"); if (!creative) throw new Error("Production requires creative strategy."); return { artifacts: [artifact("production", "production-package", { image: creative.image, video: creative.video, editing: creative.storyboard } satisfies ProductionPackage)] }; }));
  registry.register(new FunctionStage("qc", async (c) => { if (!latest<ProductionPackage>(c, "production-package")) throw new Error("QC requires production package."); return { artifacts: [artifact("qc", "qc-report", { passed: true, issues: [] } satisfies QcReport)] }; }));
  registry.register(new FunctionStage("publishing", async (c) => { const qc = latest<QcReport>(c, "qc-report"); if (!qc?.passed) throw new Error("Publishing blocked: QC did not pass."); return { artifacts: [artifact("publishing", "publication", { organic: { status: "ready" }, ads: { status: "ready" } } satisfies PublicationRecord)] }; }));
  registry.register(new FunctionStage("performance", async (c) => { if (!latest<PublicationRecord>(c, "publication")) throw new Error("Performance requires publication."); return { artifacts: [artifact("performance", "performance-report", { reach: 0, ctr: 0, cpc: 0, conversion: 0, commission: 0 } satisfies PerformanceReport)] }; }));
  registry.register(new FunctionStage("decision-learning", async (c) => { if (!latest<PerformanceReport>(c, "performance-report")) throw new Error("Decision requires performance data."); return { artifacts: [artifact("decision-learning", "decision", { outcome: "optimize", actions: ["collect real metrics", "re-evaluate product and content"], feedbackStage: "product-research" } satisfies DecisionLearning)] }));
  for (const stage of WORKFLOW_STAGES) if (!registry.has(stage)) throw new Error(`Missing workflow stage handler: ${stage}`);
  return registry;
}
