import { mkdir, writeFile, stat } from "node:fs/promises";
import { dirname, join } from "node:path";
import { WORKFLOW_STAGES } from "./workflow-schema.js";
import { WorkflowStageRegistry, FunctionStage, artifact } from "./stages.js";
import type { StageContext } from "./stage-contract.js";
import { generateContent } from "../content/index.js";
import { generateContentWithGroq } from "../ai/groq.js";
import { buildCreativeStrategy, validateCreativeStrategy } from "../creative/index.js";
import { produceCreative } from "../production/index.js";
import { publishToFacebookPage } from "../publishing/facebook.js";
import { rankProducts, scoreProducts } from "../product/index.js";
import type { Product } from "../product/types.js";
import type { ContentPackage } from "../content/index.js";
import type { CreativeStrategy, ProductionPackage, FinalContentPackage, QcReport, PublicationRecord } from "./stage-artifacts.js";
function latest<T>(context:StageContext,type:string):T|undefined{return [...context.artifacts].reverse().find(item=>item.type===type)?.data as T|undefined;}
export interface StageRegistryOptions{product?:Product;outputDir?:string;outputMp4?:string;production?:(creative:CreativeStrategy)=>Promise<ProductionPackage>;}
function finalVideoPath(production:ProductionPackage):string|undefined{const e=production.editing;if(e&&typeof e==="object"&&"finalMp4"in e&&typeof(e as any).finalMp4==="string")return(e as any).finalMp4;const v=production.video;if(v&&typeof v==="object"&&"path"in v&&typeof(v as any).path==="string")return(v as any).path;return typeof v==="string"?v:undefined;}
function contentIntegrity(product:Product,content:ContentPackage):string[]{const issues:string[]=[];if(!content.title||content.title.length>70)issues.push("content title is missing or too long");if(!content.hook||content.hook.length>180)issues.push("content hook is missing or too long");if(!content.body||content.body.length>900)issues.push("content body is missing or too long");if(!content.caption||content.caption.length>1200)issues.push("publish caption is missing or too long");if(content.caption.includes(product.url??"__NO_URL__"))issues.push("publish caption must not contain product URL");if(content.firstComment!==`🛒 พิกัดสินค้า 👇\n🔗 ${product.url}`)issues.push("first comment URL does not match selected product");if(!content.hashtags.length||content.hashtags.length>5)issues.push("hashtags must contain 1-5 tags");if(content.hashtags.some(tag=>!/^#[^\s#]{2,40}$/.test(tag)))issues.push("hashtag format is invalid");if(content.voiceScript?.length!==5)issues.push("voice script must contain exactly 5 lines");if(content.subtitleScript?.length!==5)issues.push("subtitle script must contain exactly 5 lines");return issues;}
function chooseRevisionStage(issues:string[]):QcReport["revisionStage"]{if(issues.some(issue=>issue.includes("voice script")||issue.includes("subtitle script")||issue.includes("content")||issue.includes("hashtag")||issue.includes("URL")||issue.includes("creative")||issue.includes("storyboard")))return"content-creative";return"production";}
export function createStageRegistry(options:StageRegistryOptions={}):WorkflowStageRegistry{const registry=new WorkflowStageRegistry();const live=process.env.COMMERCA_MODE==="live";
registry.register(new FunctionStage("product-input",async()=>{const p=options.product;const images=p?.images?.filter(Boolean)??(p?.image?[p.image]:[]);if(!p?.name||typeof p.price!=="number"||!p.url||!images.length)throw new Error("Manual product input requires name, price, url and at least one image.");return{artifacts:[artifact("product-input","product-input",{...p,image:p.image??images[0],images})]};}));
registry.register(new FunctionStage("product-analysis",async c=>{const p=latest<Product>(c,"product-input");if(!p)throw new Error("Product analysis requires product input.");const analysis=rankProducts([p]);if(!analysis.length)throw new Error("Product analysis produced no result.");const scorecards=scoreProducts(analysis);const best=[...scorecards].sort((a,b)=>b.score-a.score)[0];if(!best)throw new Error("Product scoring produced no result.");const selected=analysis.find(x=>x.product.id===best.productId);if(!selected)throw new Error("Selected product analysis is missing.");return{artifacts:[artifact("product-analysis","product-analysis",analysis),artifact("product-analysis","scorecard",scorecards),artifact("product-analysis","selection",selected)]};}));
registry.register(new FunctionStage("content-creative",async c=>{const selected=latest<{product?:Product}>(c,"selection");const analysis=latest<ReturnType<typeof rankProducts>>(c,"product-analysis");const product=selected?.product;const evaluated=analysis?.find(x=>x.product.id===product?.id);if(!product||!evaluated)throw new Error("Content & creative requires the selected product evaluation.");const content=process.env.COMMERCA_USE_MOCK_CONTENT==="1"&&!live?generateContent(evaluated):await generateContentWithGroq(evaluated);if(!product.url)throw new Error("Product URL is required for publishing.");if(content.productUrl!==product.url)throw new Error("Generated content URL does not match selected product.");const creative=buildCreativeStrategy(content);const creativeIssues=validateCreativeStrategy(creative);if(creativeIssues.length)throw new Error(`Creative validation failed: ${creativeIssues.join("; ")}`);return{artifacts:[artifact("content-creative","content-package",content),artifact("content-creative","creative-strategy",creative)]};}));
registry.register(new FunctionStage("production",async c=>{const creative=latest<CreativeStrategy>(c,"creative-strategy");if(!creative)throw new Error("Production requires content & creative specification.");return{artifacts:[artifact("production","production-package",options.production?await options.production(creative):await produceCreative(creative,{outputDir:options.outputDir,outputMp4:options.outputMp4}))]};}));
registry.register(new FunctionStage("qc",async c=>{const p=latest<Product>(c,"product-input");const content=latest<ContentPackage>(c,"content-package");const creative=latest<CreativeStrategy>(c,"creative-strategy");const production=latest<ProductionPackage>(c,"production-package");const issues:string[]=[];if(!p||!content||!creative||!production)issues.push("final package inputs are incomplete");if(p&&content){if(content.productUrl!==p.url)issues.push("product URL mismatch");issues.push(...contentIntegrity(p,content));}if(creative)issues.push(...validateCreativeStrategy(creative));const v=production?finalVideoPath(production):undefined;if(!production?.image)issues.push("missing image output");if(!v)issues.push("missing final video output");if(!production?.voice)issues.push("missing voice output");if(!production?.subtitle)issues.push("missing subtitle output");if(v){try{if((await stat(v)).size<1000)issues.push("final video file is empty or invalid");}catch{if(live)issues.push("final video file does not exist");}}return{artifacts:[artifact("qc","qc-report",{passed:issues.length===0,issues,...(issues.length?{revisionStage:chooseRevisionStage(issues)}:{})} satisfies QcReport)]};}));
registry.register(new FunctionStage("final-package",async c=>{const qc=latest<QcReport>(c,"qc-report");const p=latest<Product>(c,"product-input");const content=latest<ContentPackage>(c,"content-package");const creative=latest<CreativeStrategy>(c,"creative-strategy");const prod=latest<ProductionPackage>(c,"production-package");if(!qc?.passed)throw new Error("Final package requires passed QC.");if(!p||!content||!creative||!prod)throw new Error("Final package inputs are incomplete.");const videoPath=finalVideoPath(prod);if(!videoPath)throw new Error("Final package requires final video.");if(!p.url||content.productUrl!==p.url)throw new Error("Final package blocked: product URL is missing or mismatched.");const firstComment=content.firstComment??`🛒 พิกัดสินค้า 👇\n🔗 ${p.url}`;const organic:Record<string,unknown>={status:live?"publishing":"ready",platform:"facebook",caption:content.caption,hashtags:content.hashtags,callToAction:content.callToAction,productUrl:p.url,firstComment,videoPath};let publishedOrganic=organic;if(live){const result=await publishToFacebookPage({videoPath,caption:content.caption});publishedOrganic={...organic,status:"published",provider:result.provider,postId:result.id,permalink:result.permalink};}const publication:PublicationRecord={organic:publishedOrganic,ads:{status:"ready",platform:"meta",videoPath,productUrl:p.url}};const finalPackage:FinalContentPackage={product:p,content:{...content,firstComment},creative,production:{...prod,video:{path:videoPath}},qc,publish:publication};const dir=options.outputDir??process.env.COMMERCA_OUTPUT_DIR??"./output";const outPath=options.outputMp4?join(dirname(options.outputMp4),"final-content-package.json"):join(dir,"final-content-package.json");await mkdir(dirname(outPath),{recursive:true});await writeFile(outPath,JSON.stringify(finalPackage,null,2),"utf8");await writeFile(`${dirname(outPath)}/post.txt`,`${content.caption}\n\n${firstComment}\n`,"utf8");return{artifacts:[artifact("final-package","publication",publication),artifact("final-package","final-package",finalPackage)]};}));
for(const stage of WORKFLOW_STAGES)if(!registry.has(stage))throw new Error(`Missing workflow stage handler: ${stage}`);return registry;}
